tic
x=45
y=90
tic
sind(x+y)==sind(x)*cosd(y)+cosd(x)*sind(y)
toc
tic
sind(x-y)==sind(x)*cosd(y)-cosd(x)*sind(y)
toc
tic
cosd(x+y)==cosd(x)*cosd(y)-sind(x)*sind(y)
toc
tic
cosd(x-y)==cosd(x)*cosd(y)+sind(x)*sind(y)
toc
tic
sind(x)+sind(y)==2*sind((x+y)/2)*cosd((x-y)/2)
toc